name: Android CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download and Install Android SDK
        run: |
         wget https://dl.google.com/android/repository/sdk-tools-linux-30.0.3.zip
         unzip sdk-tools-linux-30.0.3.zip -d $HOME/android-sdk
         echo 'export ANDROID_SDK_ROOT=$HOME/android-sdk' >> $GITHUB_ENV
         echo 'export PATH=$PATH:$HOME/android-sdk/tools/bin' >> $GITHUB_ENV

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign app APK
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 30.0.3

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: xqe-sesame-${{ github.event.release.tag_name }}.apk
          path: ${{ steps.sign_app.outputs.signedFile }}
          repo-token: ${{ github.token }}
          content-type: application/zip
